apiVersion: v1
kind: Pod
metadata:
  name: servicecenter
  labels:
    app: servicecomb
spec:
  containers:
    - name: servicecenter
      image: servicecomb/service-center:1.0.0-m1
      ports:
        - containerPort: 30100
      resources:
        limits:
          cpu: "1"
---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: service-center
spec:
  selector:
    app: servicecomb
  ports:
  - protocol: TCP
    nodePort: 30100
    port: 30100
    targetPort: 30100
  type: NodePort