apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  ports:
  - port: 9999
    name: http
  selector:
    app: server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: xiaoliang/server-io-go
        ports:
        - containerPort: 9999
---
