apiVersion: v1
kind: Pod
metadata:
  name: client-mesher
  labels:
    app: perf
    version: 0.0.1
spec:
  containers:
    - name: client
      image: xiaoliang/client-go
      env:
        - name: TARGET
          value: http://server-mesher/
        - name: PORT
          value: 9000
        - name: http_proxy
          value: http://127.0.0.1:30101/
      resources:
        limits:
          cpu: "1"
    - name: mesher
      image: xiaoliang/mesher
      args:
        - --service-ports
        - rest:9000
      env:
        - name: SERVICE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CSE_REGISTRY_ADDR
#          value: http://service-center.default:30100
          value: http://192.168.1.94:30100
        - name: SERVICE_PORTS
          value: rest:9000
      ports:
        - containerPort: 30101
        - containerPort: 30102
        - containerPort: 6060
      resources:
          limits:
            cpu: "1"
---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: client-mesher
spec:
  selector:
    app: perf
  ports:
  - protocol: TCP
    name: client
    port: 30107
    nodePort: 30107
    targetPort: 9000
  type: NodePort