apiVersion: v1
kind: Service
metadata:
  name: cons
  labels:
    app: cons
spec:
  type: NodePort
  ports:
  - port: 9000
    nodePort: 32001
  selector:
    app: cons
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cons
spec:
  template:
    metadata:
      labels:
        app: cons
    spec:
      containers:
      - name: cons
        image: xiaoliang/client-go
        env:
        - name: TARGET
          value: http://server:9999
        ports:
        - containerPort: 9000
---
