apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    app: default
    version: 0.0.1
spec:
  containers:
    - name: server
      image: xiaoliang/server-go
      ports:
        - containerPort: 9999
      resources:
        limits:
          cpu: "1"